tasks:
  - name: assign-to-project
    on:
      issues:
        types: [opened]
      pull_request:
        types: [opened]
    condition: (await getTeamMembers('capacitor')).includes(payload.sender.login)
    config:
      columns:
        issue: 10495656
        pr: 10495659
        draft-pr: 10495658
